### ISSUE TITLE
Implement scraper API routes

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#115]
Need to implement the scraper routes (i.e. `/api/courses`) so that we can start actually providing the frontend with data. This also means that we need to get to a point on the frontend that we're actually requesting data, or in other words, the frontend will define what routes they need, and we will then satisfy it for them.

For instance, the frontend may send a query such as `/api/courses?text="CS"` and we would return `CSCE 111, 121, ...`. Alternatively, `/api/terms` would simply return all of the current available terms that one can choose out of. 

Depending on the size of them, this may be an epic that has subtasks for each of the different routes. However I am expecting most of them to be no more than 10 lines each.

Routes that I can think of(names are TBA):
- `/api/terms` - for getting all the possible terms (to put on the landing page drop down)
  - Parameters: none
  - May want to send a fixed amount, then send more if they scroll up/down?
- `/api/course/search/` - for searching courses for the given term - only autocompletes
  - Parameters: the current search text in the course search box, as well as term?
  - Will need to decide how we filter what to send, but generally the results should be sorted with the smallest result first (i.e. given "CS", send `CSCE 121` before `CSCE 221`)
- `/api/sections/` - Give all sections for the given course
  - Parameters: Course (id?), term
  - Returns: Section data w/
    - Instructor GPA distribution (if applicable), meeting times, if there are web / honors classes
- `/api/course/` - Give all of the data about a given course?
  - Parameters: Subject, course #, term
  - Returns: Course title(i.e. "Programming Languages" for 314) & credit hours

Edit by Ryan:
When creating views for the other models, the results should be formatted the same as the expected data in the test cases I created:
`/api/terms`:
```
{
    "202031": "Fall 2020 - College Station",
    "201931": "Fall 2019 - College Station",
    "201831": "Fall 2018 - College Station",
}
```
`/api/sections`:
```json
[
    {
        "id": "10923201931",
        "crn": 10923,
        "instructor_gpa": null,
        "instructor_name": "John M. Moore",
        "honors_only": null,
        "meetings": [
            {
                "id": "4683040",
                "days": [
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false
                ],
                "start_time": "11:30:00",
                "end_time": "12:20:00",
                "type": "LEC"
            },
            {
                "id": "4683041",
                "days": [
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false
                ],
                "start_time": "15:00:00",
                "end_time": "15:50:00",
                "type": "LAB"
            },
        ],
        "section_num": "503",
        "web_only": null
    },
    {
        "id": "39493201931",
        "crn": 39493,
        "instructor_gpa": null,
        "instructor_name": "John M. Moore",
        "honors_only": null,
        "meetings": [
            {
                "id": "4911320",
                "days": [
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false
                ],
                "start_time": "11:30:00",
                "end_time": "12:20:00",
                "type": "LEC"
            },
            {
                "id": "4911321",
                "days": [
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false
                ],
                "start_time": "19:00:00",
                "end_time": "19:50:00",
                "type": "LAB"
            }
        ],
        "section_num": "504",
        "web_only": null
    },
]
```
Note that it's a little tricky to format the data like this, you'll have to override the `list(self, request, *args, **kwargs)` method for `ListAPIView` in order to return a dictionary with ids as the keys instead of the default behavior (list comprehension with serializer called on each object in the queryset)
`/api/course`:
```
{
    'title': 'Sports Law',
    'credit_hours': None,
}
```
`/api/course/search`:
```
{'results': ["CSCE 181", "CSCE 315"]}
```

**Comment by gannonprudhomme** [comment]
@firejake308 Do all of these routes sound good / make sense? Anything you think should be added or changed?

**Comment by gannonprudhomme** [comment]
Myself or @ryan-conn will make tests for these routes prior to a PR for this is made so we can define what the routes should do concretely.

**Comment by ryan-conn** [comment]
For `/api/terms`, we'll want to create a function to convert term codes to a text description. For example, `202011` should become `Spring 2020 - College Station`. There's a pattern to this: `2020` is the year, the first `1` means Spring, and the second `1` means College Station. Here's a list of the last 20 terms so that we can see what other numbers correspond to:
```

[
  {
    "code": "202011",
    "description": "Spring 2020 - College Station"
  },
  {
    "code": "202012",
    "description": "Spring 2020 - Galveston"
  },
  {
    "code": "202013",
    "description": "Spring 2020 - Qatar"
  },
  {
    "code": "202015",
    "description": "Spring 2020 - Half Year Term"
  },
  {
    "code": "201931",
    "description": "Fall 2019 - College Station"
  },
  {
    "code": "201932",
    "description": "Fall 2019 - Galveston"
  },
  {
    "code": "201933",
    "description": "Fall 2019 - Qatar"
  },
  {
    "code": "201935",
    "description": "Fall 2019 - Half Year Term"
  },
  {
    "code": "201921",
    "description": "Summer 2019 - College Station"
  },
  {
    "code": "201922",
    "description": "Summer 2019 - Galveston"
  },
  {
    "code": "201923",
    "description": "Summer 2019 - Qatar"
  },
  {
    "code": "201911",
    "description": "Spring 2019 - College Station"
  },
  {
    "code": "201912",
    "description": "Spring 2019 - Galveston"
  },
  {
    "code": "201913",
    "description": "Spring 2019 - Qatar"
  },
  {
    "code": "201915",
    "description": "Spring 2019 - Half Year Term"
  },
  {
    "code": "201941",
    "description": "Full Yr Professional 2019-2020"
  },
  {
    "code": "201831",
    "description": "Fall 2018 - College Station"
  },
  {
    "code": "201832",
    "description": "Fall 2018 - Galveston"
  },
  {
    "code": "201833",
    "description": "Fall 2018 - Qatar"
  },
  {
    "code": "201835",
    "description": "Fall 2018 - Half Year Term"
  }
]
```
