### ISSUE TITLE
Implement course picker

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#123]
In order to select classes in their schedule, users will first see a single course select card to select a course, then be able to click a button to add a class/course select card to their schedule. I made a quick draft of what it should look like once a few classes have been added here (note that this component should be able to scroll):
![image](https://user-images.githubusercontent.com/28655462/71758444-60dea500-2e65-11ea-9d6d-f8dc8f6df427.png)
This is by no means a final design, and we don't have to use the design, I just wanted to make something to explain the concept better

**Comment by gannonprudhomme** [comment]
Also, the "Add New Course" button should be fixed to the bottom of the course pickers, such that if the course picker is expanded it'll shift down.

**Comment by gannonprudhomme** [comment]
@f4alt You'll most likely have to change / add some Redux, which I would consult @firejake308 for

**Comment by gannonprudhomme** [comment]
@sheldontheking Do you have any update on this?

**Comment by gannonprudhomme** [comment]
You can see my progress for this on `frontend/course-picker`

**Comment by gannonprudhomme** [comment]
After working on this for a bit, some changes I think we need to make to `CourseSelectCard`:

- Make the top bar the same size opened and closed, is wonky when you're rapidly expanding and collapsing it. I'd say probably increase the size when it's expanded and reduce the size when it's collapsed.
![chrome_drB9kAW5Pj](https://user-images.githubusercontent.com/7295783/76906266-96463c80-6871-11ea-8bb4-9884a41a8bb2.png)
![chrome_ncV7WBr52W](https://user-images.githubusercontent.com/7295783/76906273-99412d00-6871-11ea-87f8-e84f243b8acc.png)
- Make the remove & collapse text hightlight / show some indication on hover
- Probably make clicking the entire bar collapse/expand the card (other than remove ofc)
- Maybe add a remove icon when it's collapsed

Thoughts @firejake308 @ryan-conn ?

**Comment by firejake308** [comment]
> Make the top bar the same size opened and closed

Seems reasonable to me

> Make the remove & collapse text hightlight / show some indication on hover

I think the usual material way of showing buttons is to make the background like rgba(0, 0, 0, 0.7) or something on hover

> Probably make clicking the entire bar collapse/expand the card (other than remove ofc

May or may not be intuitive, not sure

> Maybe add a remove icon when it's collapsed

Obviously not required for functionality of the website, but could improve ease of use if we find a good place to put it

**Comment by firejake308** [comment]
Also, Remove and Collapse are shown in the wrong font in your browser. Are you using Chrome?

**Comment by gannonprudhomme** [comment]
> Also, Remove and Collapse are shown in the wrong font in your browser. Are you using Chrome?

Yep

**Comment by ryan-conn** [comment]
I agree with all of your proposed changes, and I also think we should change the remove icon from an X to a trash can, since that's consistent with availability cards and looks better imo. Also I feel like at some point we should make an animation for expanding/collapsing course cards but that's in no way a priority

**Comment by gannonprudhomme** [comment]
> I agree with all of your proposed changes, and I also think we should change the remove icon from an X to a trash can, since that's consistent with availability cards and looks better imo. Also I feel like at some point we should make an animation for expanding/collapsing course cards but that's in no way a priority

Yeah I definitely think we should add animations for the expanding / closing. Also think there should be some form of animation when deleting a card as it looks kind of confusing having them disappear. But yeah we can wait until we have all of the functionality down and such, probs can do it in Frontend V0.4
