### ISSUE TITLE
Implement /api/sections

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#136]
Need to implement the /api/sections route. From #115: 

- `/api/sections/` - Give all sections for the given course
  - Parameters: Course (id?), term
  - Returns: Section data w/
    - Instructor GPA distribution (if applicable), meeting times, if there are web / honors classes

See `scraper/tests/api_tests.py` for more specific details on how it should all look.

In `scraper/urls.py`, you'll need to add to `urlpatterns`:
```python
path("sections", views.ListSectionView.as_view())
```

You'll also need to add the respective view to `scraper/views.py`

Try to get this done by Tuesday 2/11. If you have any problems / won't make this deadline, then no worries, just let us know!

**Comment by gannonprudhomme** [comment]
You'll need to wait until #134 is merged until `backend/master` to begin, as it provides the tests for these routes as well as some examples on how it should all look.

**Comment by gannonprudhomme** [comment]
@btgathright Can you recreate the pull request using the `backend/scraper/api/sections` branch? I moved your changes to it, which I mentioned in #139

**Comment by ryan-conn** [comment]
Implemented by #142, so I'm closing this issue
