### ISSUE TITLE
Correct Redux Types

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#140]
There are a few Redux types that need to be corrected to closer match the backend models. These include:

- Course
  - `courseNum` should be a string, as some courses have characters in them, such as `LAW 7200S`
- Section
  - `sectionNum` should be a string, as some sections can have characters, i.e. `CSCE 121 - M99`
  - `courseNum` should be a string, see above.
  - Should have the `crn` field, rather than the Meeting (as crn's are section specific)
  - ~~Shouldn't have `minCredits`/`maxCredits`, as it's a property of the Course object (although this depends on how the models are used on the site)~~
- Meeting
  - Remove crn field, see above.
  - (Side-note): While it's not handled in the actual Meeting type, `meetingDays` should have the first index be Monday, rather than Sunday (in Course Select Card's `SectionSelect`)

Is there even a need for `Department`? I can't imagine when it'll be used

This won't really be needed until #115 is completed and merged, but I'm just writing them down so we know once we start connecting the frontend to the backend.

**Comment by firejake308** [comment]
Does the server still return an array of all 7 days of the week for meeting days? If so, I am currently translating the 7-day week to a 5-day week within `Schedule.tsx`, so translating that in the type file will need us to remove the redundant translation in the `<Schedule />` component

**Comment by gannonprudhomme** [comment]
Yeah we are. Like I mentioned, it just needs to be handled to have Monday be the first index in the case of the CourseSelectCard

**Comment by gannonprudhomme** [comment]
Already did a bit of these for #144 so gonna make a PR for it real quick

**Comment by gannonprudhomme** [comment]
Might want to just keep `minCredits` for the Section as we could easily send it with `api/sections`. Otherwise if we ever wanted to access the credit hours we'd have to get it from `api/course/search` since that's the only place we deal with the Course on either end, which I don't think we want to have to deal with (plus that route is better suited for just text anyways). Thoughts @firejake308 @ryan-conn ?

**Comment by firejake308** [comment]
I agree with leaving credits in the Section. Also, I think we can get rid of Department as well.
