### ISSUE TITLE
Add full course selection / schedule view page

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#145]
Need to add the full blown main course selection / schedule viewing page.

![Figma_ZIpPpAVJmL.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/5f8414c8-0eb7-43a5-b259-61f2dc3ef4dc)

Some of these details are tenatative, but this is a pretty good idea of how the final page will look.

This task won't include the creation of the middle column (configure and schedules), just the outline for it.

**Comment by firejake308** [comment]
Do you want to use the all-in-one layout or the step-by-step layout?

**Comment by gannonprudhomme** [comment]
> Do you want to use the all-in-one layout or the step-by-step layout?

I’d say the all-in-one layout
