### ISSUE TITLE
Connect landing page with the main scheduling page

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#146]
For the landing page, we need to make it so that once the user clicks a term, it automatically brings them to the main scheduling page (and saves the term in Redux)

**Comment by gannonprudhomme** [comment]
This shouldn't be too hard, so I'm gonna start on this

**Comment by gannonprudhomme** [comment]
@firejake308 I assume I should make the term stored in the Redux store/root state or w/e

**Comment by firejake308** [comment]
Yes
