### ISSUE TITLE
Add grade distribution route

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#148]
Need to add the /api/grades route so the frontend can retrieve grade distributions as needed.

`/api/grades` route:
- Params:
  - Instructor (name/id)
  - Subject / department
  - Course number
  - ~~Term~~
- Returns:
  - A dictionary with the counts of each grade type (A, B, C, D, F, Q-drop, etc) as well as the average GPA. See `GradeManager.instructor_performance` for more details.

Just btw, you access `instructor_performance` by calling `Grades.objects.instructor_performance`

**Comment by ThatJuanGuy** [comment]
Do I branch this off of backend/master?

**Comment by gannonprudhomme** [comment]
Yep
