### ISSUE TITLE
Split up Redux files into separate files

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#153]
Per #151, we need to split up the Redux files into logical pieces. For instance, in `redux/availability`, we would have a `reducers.ts`, `actions.ts`, etc so each piece can be logically separated which should make things much more organized and easier to read.

**Comment by firejake308** [comment]
Oops for accidentally coding the issue. Do y'all want this done before or after #151 is merged?

**Comment by gannonprudhomme** [comment]
I'd def say after #151 just cause we'd have to make the changes all over again
