### ISSUE TITLE
Material UI Button bug

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#168]
Messing around with the course selection component, I realized that buttons in material UI have a bug where if the tab loses focus, the animation for clicking a button will glitch out:
![what](https://user-images.githubusercontent.com/28655462/77689534-ce373900-6f6f-11ea-9870-a010df55e1ad.gif)

We can probably fix this by making a custom button component and stopping animation when the tab loses focus, see [this](https://material-ui.com/customization/components/#overriding-styles-with-classes) page, but I haven't tried implementing it myself so I'm not sure if this will work.

**Comment by gannonprudhomme** [comment]
Now that I think about it, isn't this more of a MaterialUI bug? I don't think this is something we need to fix on our end personally

**Comment by firejake308** [comment]
Incidentally, I recently updated the MaterialUI library in our `package-lock.json`. Does the bug still exist in the new version?

**Comment by ryan-conn** [comment]
Yeah, it does. Upon digging deeper, [apparently this has been an issue since 2017](https://github.com/mui-org/material-ui/issues/7900), which has since been closed. I commented on the original issue so hopefully it'll be reinvestigated. As such I'll close this issue but keep an eye out on the one in the material UI repo
