### ISSUE TITLE
Course Select Card improvements

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Rev-Registration#172]
Right now `ExpandedCourseCard` calls the `fetch` to retrieve all of the sections from `api/sections`, and if you collapse then expand the card it will fetch again even though all of the data remains the same.

In order to fix this, we need to shift the fetching over to the parent `CourseCard` component so we don't make unneeded API calls.

**Comment by gannonprudhomme** [comment]
Look good? @firejake308

**Comment by firejake308** [comment]
@gannonprudhomme is this still a problem? I might've misunderstood the setup, but I'm not able to replicate it at the moment

**Comment by gannonprudhomme** [comment]
![request bug](https://user-images.githubusercontent.com/7295783/79052434-2458dd00-7bfc-11ea-9174-1ed5df880c5f.gif)

Yep (this is on the GCP deployment but it most likely still applies on `frontend/course-card-route-connection`)

**Comment by firejake308** [comment]
Ah, k, I was looking at the wrong API route
