### ISSUE TITLE
Make honors/web only selection allow excluding honors/web classes

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#176]
For the basic course select, right now there are only 2 options: honors only and not honors only. This is a little up to interpretation on what it should do if the boxes aren't checked: to exclude non-honors/web sections or to choose any section.

Because of this, and the fact that I see valid use cases for wanting either of these behaviors, we should make this into a three-way selection that lets the user exclude honors, have no preference, or only use honors sections. Here's a draft of what this could look like:
![image](https://user-images.githubusercontent.com/28655462/78460020-f9faa300-7682-11ea-8d56-cff1f5b85ca4.png)
Suggestions are welcome for improvements, but we'll want this functionality in some form.

**Comment by gannonprudhomme** [comment]
If possible I think I'd rather it be a single checkbox with multiple state (green check for honors only, red x for no honors), or maybe a dropdown with text options?

**Comment by firejake308** [comment]
![image](https://user-images.githubusercontent.com/10082177/79049262-2fa20d80-7be8-11ea-8dea-859401e9d280.png)
I've put these four possible designs on Figma; which looks best to y'all?

**Comment by gannonprudhomme** [comment]
I think I like the top right one the best, but we can discuss it in the meeting tomorrow.

**Comment by gannonprudhomme** [comment]
We decided on the bottom right one from Adel's mockups in the 4/12 meeting.
