### ISSUE TITLE
Figure out how to explain the website

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#187]
We first need to figure out what text to add to the landing page in order to the landing page.

Second, I think it might be beneficial if we had a gif or video on the homepage showing what the website actually does.

Also, I think we need some visual that would show them that you can drag on the schedule to make availabilities, such as through an interactive tutorial or a gif 

Might also be worth explaining that the schedules generate random combinations, so if you don't like the combinations it gives you you can try to regenerate it (assuming we don't set a consistent seed in #167)

**Comment by firejake308** [comment]
Would a step-by-step design help with guiding the flow of a user through the website?

**Comment by gannonprudhomme** [comment]
> Would a step-by-step design help with guiding the flow of a user through the website?

Yeah I think it would probably help, however I still think directly explaining / showing them that you have to drag to make an availability is inevitable.

**Comment by gannonprudhomme** [comment]
Closing in favor of #496
