### ISSUE TITLE
Connect "Fetch Schedules" with /scheduler/generate

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#193]
Once #145, #169, #149, and #165 are completed, we need to connect generate schedules with the route for the scheduling algorithm. 

When I implemented this on my fork, since /scheduler/generate on the backend uses (or at least should use) the `SectionSerializer`, we should be able to use the `parseMeetings` function from #144 to implement this pretty easily.

**Comment by gannonprudhomme** [comment]
It'll also have to be a POST request since GET requests can't have a request body, which means we'll need to figure out CSRF authentication or w/e. In order to get it working I had to disable the CSRF middleware. As such, we'll need to pass as CSRF token from the backend to the frontend in order for use to do these POST requests to the backend.

**Comment by gannonprudhomme** [comment]
After reading about it more, we might just be able to disable it for the view made in #165 , since the route doesn't actually modify anything on the server (which is what CSRF is protecting against), as it's really just a GET request in disguise. From [here](https://owasp.org/www-community/attacks/csrf):

`
CSRF attacks target functionality that causes a state change on the server, such as changing the victim’s email address or password, or purchasing something. Forcing the victim to retrieve data doesn’t benefit an attacker because the attacker doesn’t receive the response, the victim does. As such, CSRF attacks target state-changing requests.
`

**Comment by firejake308** [comment]
Makes sense to me. I'm in favor if disabling CSRF for this view then.

**Comment by gannonprudhomme** [comment]
We also need to make it so that if a course card has specific sections chosen, but they're on the "Basic" customization level, those sections shouldn't be sent to the `/scheduler/generate` route. Likewise if they have "web only" selected but they're on "Section", don't include the filter.
