### ISSUE TITLE
Prevent multiple "Generate schedules" submissions

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#205]
We should disable the "fetch schedules" button once it has been submitted and is waiting to retrieve a response from the database, so that users can't stack multiple requests upon each other.

**Comment by firejake308** [comment]
Would y'all prefer to replace Generate Schedules with a loading icon, or to disable/grey out the button, or both?

**Comment by gannonprudhomme** [comment]
I was thinking both, but I think we really just gotta see which one feels the best

**Comment by gannonprudhomme** [comment]
Do you think we should do this and #206 in the same PR?

**Comment by firejake308** [comment]
Yes
