### ISSUE TITLE
Add loading icon/displaying to course cards and schedule preview

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#206]
Need to add some form of loading indicator to the course card (for sections) and the schedule preview in order to display to the user that a request has been sent out and is waiting for it to be returned.

We can probably just add a transparent gray overlay to it and add a typical loading indicator (spinning wheel thing)

Might also want to include in this the disabling of the `Fetch Schedules` button while the request is being retrieved to prevent the user from stacking on `/scheduling/generate` calls

**Comment by firejake308** [comment]
This probably belongs in #196

**Comment by gannonprudhomme** [comment]
You think? Honestly I think this is like "extra" functionality and I saw #196 and #188 as like the barebones of the scheduling page, so I think this would be fine as a separate issue/PR imo. Plus that way we have a PR dedicated to only that part of the functionality.

**Comment by gannonprudhomme** [comment]
Also just a thought, but we might want to show something on the schedule preview when no schedules were generate (i.e. say "No possible schedules"). That way if they have previously generated schedules, then generate new ones and no new ones are found it'll be obvious. 

That being said, it might be apparent that there aren't new ones if the old ones aren't replaced, but I think it'll benefit us to be explicitly say it
