### ISSUE TITLE
Show honors sections in Course Cards

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#230]
We need to show that a specific section is honors so the users can figure out which sections they want. In the 4/26 meeting we decided that we're going to 

We need to make the course card's section displaying to split the sections-instructor grouping to put honors and non-honors sections into different "instructor-groups". Below is what I have mocked up for it, albeit with the out-of-date designs. I personally like the one that explicitly says `Honors` rather than use an icon as I think it's much more explicit. For the icon I was thinking we'd also have it just show a tooltip that said "honors"/"honors sections" on hover.

![Figma_8ecRm1LhQG.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/9a0fda3e-649f-4cb3-9b42-254c7df2125d)
![Figma_TFhWZryiqX.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/bc053178-9a5a-4b6f-81e0-7886588c9e3c)

**Comment by firejake308** [comment]
This should be pretty ez once #221 is merged
