### ISSUE TITLE
Align the section type/day/time columns in SectionSelect

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#238]
After working on #184 I realized that the section type / day / time columns weren't aligned with each other

![chrome_m3t01jk59P.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/e1267165-9995-4671-90f6-607923ae15fe)

We should align them so they look something like this (ignore the periods, just did that so I could get my point across lol). I don't think each actual section's columns need to align with different ones, but the meetings within a single section should align with each other. 
![chrome_ADcMwU3f1h.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/24ed24ab-aa0f-406d-9c55-d3e6936d0a4b)

**Comment by firejake308** [comment]
I think using an HTML `<table>` would help us with this. I can make a PR to convert the current layout to use `<table>` if you'd like

**Comment by ryan-conn** [comment]
Sure, that's what I was thinking we would have to do to align columns so go ahead

**Comment by gannonprudhomme** [comment]
Yeah feel free to do this, I tried doing it with `display: grid` and stuff then got too frustrated and stopped lol
