### ISSUE TITLE
Change tuple(generator) expressions to list comprehensions

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#240]
I woke up at 5 am and couldn't get back to sleep, so I wondered "how does python efficiently create tuples from generator expressions if it doesn't know the number of items beforehand?", because apparently that's the kind of thing that goes through my head at 5 am. I realized the answer is that it converts the generator into a list and then turns the list into a tuple, which means that tuple comprehensions are ~1/2 the speed of just using a list comprehension. Here's an example I made to illustrate this:
```python
n = 100_000
times = 10_000
for _ in range(times):
    l = [x for x in range(n)]
print(f"{time() - start}s for list comprehension")

start = time()
for _ in range(times):
    l = tuple(x for x in range(n))
print(f"{time() - start}s for tuple comprehension")
```
Output:
```
22.481091737747192s for list comprehension
48.413695096969604s for tuple comprehension
```

Thus, whenever we use `tuple(generator)` based on my incorrect assumption that doing so could be done efficiently, we should change them to list comprehensions. Not that high priority since it doesn't add any functionality, but it's a really easy change to make that provides free speedup.

**Comment by gannonprudhomme** [comment]
@ryan-conn this has been in Todo for awhile, do you still plan on doing it?

**Comment by ryan-conn** [comment]
Decided not to implement as this won't really make much of a performance improvement
