### ISSUE TITLE
Optimize updateCourseCardAsync

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#241]
The way we calculate sections for meetings right now seems unnecessarily complicated: first we create a section for each section in the response, then we find all meetings belonging to that section and only return the meetings, then sort the meetings to determine which section they were originally in and create `SectionSelected` objects based on that. I propose that we do the following:
- Instead of giving each `Meeting` a `Section`, give the `Section` type an array of its meetings
- Directly return an array of sections with their meetings in `parseMeetings` and completely remove `meetingsToSectionSelected`

Also, since the only property exclusive to `SectionSelected` is `selected`, we could either move it to the `Section` type (and just give it a default value of `null`), or keep a boolean array of whether sections are selected in the state for each course card. It seems a little overkill to make another class just to add one attribute to `Section` when we can just ignore the property when we don't need it.

Let me know what you guys think @gannonprudhomme @firejake308, I don't see any reason we shouldn't be able to make these changes but perhaps I'm missing something that you guys noticed when working on those functions

**Comment by firejake308** [comment]
Seems reasonable to me

**Comment by gannonprudhomme** [comment]
Yeah makes sense to me

**Comment by ryan-conn** [comment]
Which way would we prefer: keeping `SectionSelected` or making `selected` an attribute of `Section`? I can see either way but imo just having a class for `Section` looks cleaner so I'm leaning towards doing it that way

**Comment by firejake308** [comment]
Yeah, `SectionSelected` was always a work-around
