### ISSUE TITLE
Fix App Engine Continuous Deployment

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#250]
GCP Deploy is down for some reason, so I need to look into fixing it

**Comment by firejake308** [comment]
@gannonprudhomme does one of your recent PRs address this?

**Comment by gannonprudhomme** [comment]
Yeah sort of. This really was to look into another issue (which was actually that Google App Engine had too many versions & we needed to delete some), but my current PR does technically close this so I'll use it as well. Good catch, completely forgot about this
