### ISSUE TITLE
Make instructors selectable in SectionSelect

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#259]
You should be able to select a professor in the SectionSelect's `SECTION` customization level, which would select/deselect all of the sections for that professor. 

(insert design here)

**Comment by firejake308** [comment]
I have a couple designs for this in Figma, we can dicsuss these at 10/4 meeting

**Comment by ryan-conn** [comment]
Here are the designs I made a couple weeks back, I believe we decided the left looked better but we should talk about it more before making a final decision:
https://media.discordapp.net/attachments/689540052870627342/763250327323017216/unknown.png

Also the mockup Adel made (that includes icons), looks the best to me but would involve more changes:
![image](https://user-images.githubusercontent.com/28655462/97595649-e4a7e600-19d1-11eb-9346-62106ac5b117.png)
