### ISSUE TITLE
Separate honors/non-honors sections for Grades.instructor_performance

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#261]
Since honors and non-honors section for the same course & professor's grade distributions typically vary, we should add an option to `GradeManager.instructor_performance` that only includes honors / non-honors sections. Should just be able to add a `section__honors=honors_param` to the `self.prefetch_related("section").filter(...)` call. We'll also have to change the call in the `SectionSerializer` to make sure that it uses the correct calls.

**Comment by firejake308** [comment]
Alright, time to finally get this done
