### ISSUE TITLE
Add tooltips to instructional methods for meetings

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#298]
Since the names "LEC", "LAB", "INS", "RES", etc. can be confusing at first glance, we should add tooltips to them (similar to the GPA tooltip) where they are underlined to indicate that hovering will do something, and the tooltip contains the full text ("Lecture", "Lab", etc)

**Comment by gannonprudhomme** [comment]
For this, you need to change the meeting type text in `SectionSelect.tsx` (in `frontend/src/components/SchedulingPage/CourseSelectColumn/ExpandedCourseCard/SectionSelect/SectionSelect.tsx`) to be underlined, and add a tooltip that displays what the meeting type is. You can view a list of the meeting types and their explanations on our [wiki here](https://github.com/aggie-coding-club/Rev-Registration/wiki/Meeting-Types). 

To actually add a tooltip you can use [Material UI's Tooltip component](https://material-ui.com/components/tooltips/#tooltip), then surround the meeting type in `SectionSelect.tsx` with it (you'll set what the tooltip text is in the `title` attribute of the Tooltip). You can see an example of the tooltip being used in our codebase in our [GradeDist component](https://github.com/aggie-coding-club/Rev-Registration/blob/master/autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/GradeDist/GradeDist.tsx#L56).

**Comment by gannonprudhomme** [comment]
| count | meeting type | meeting type description |
|-------|--------------|--------------------------|
| 8072  | LEC          | Lecture                  |
| 3719  | LAB          | Laboratory               |
| 2345  | RES          | Research                 |
| 1401  | EXAM         | Examination              |
| 864   | INS          | Independent Study        |
| 467   | SEM          | Seminar                  |
| 398   | PRAC         | Practicum                |
| 280   | REC          | Recitation               |
| 144   | CLD          | Clinic                   |
| 9     | CMP          | Competition              |
| 6     | PRL          | Private Lesson           |
| 2     | CLAS         | Class                    |
| 1     | INT          | Internship               |
