### ISSUE TITLE
Redirect to landing page or alert user when scheduling page is open with no term selected

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#301]
Since using the scheduling page with no term selected is completely useless, I propose that we just redirect back to the landing page if this happens. This is possible if you don't have cookies enabled, if you've never selected a term, and probably a couple other situations, so it would be nice to just redirect users to prevent confusion.

**Comment by firejake308** [comment]
Do we still want to implement this now that #349 is a thing?

**Comment by gannonprudhomme** [comment]
> Do we still want to implement this now that #349 is a thing?

Huh that's actually a good point, I would still think so just because when you're on `/schedule` it does expect for `term` to be non-null, but given that you can now select a term from it I might be fine not implementing this. At the very least, we need to indicate that you cannot do anything until you select a term, which I don't think will be obvious just by it showing `Select Term` in the NavBar when term is null. Thoughts @ryan-conn ?

**Comment by ryan-conn** [comment]
There are 2 solutions that make sense to me: either replace the page contents with some text that says "click a term to view your schedules" or something like that", or just redirecting to the homepage. I think redirecting to the homepage would be better, since putting text on the page doesn't really add anything to the site and if someone's visiting for the first time on the schedule page for whatever reason, they'll see a more thorough explanation if we redirect

**Comment by eelyort** [comment]
Should I go ahead and redirect when there's no term found then? Or did you want to discuss it more?

**Comment by gannonprudhomme** [comment]
Yeah I think we're in agreement: when you're on the scheduling page (that is, when the `SchedulingPage.tsx` component is rendering), you should check if the term is `null`, and if it is, redirect to the root route.

To check if the term is null, you need to retrieve the term from our Redux state. You do this by doing a [`useSelector`](https://react-redux.js.org/api/hooks#useselector) call (we use these a bunch, just do a search for it in the project and you'll see an example). Should look something like `const term = useSelector<RootState, string>((state) => state.term);`. Then, when that's null/falsy, redirect to the root route. Let us know if you have any other questions!

**Comment by gannonprudhomme** [comment]
For testing this:

We use `navigate` in `SelectTerm` for navigating to `/schedule` when we select a term, so you can look at `tests/ui/SelectTerm.test.tsx`, specifically the `Redirects to schedule when a term is selected` test [here](https://github.com/aggie-coding-club/Rev-Registration/blob/master/autoscheduler/frontend/src/tests/ui/SelectTerm.test.tsx#L98). Really the only thing that applies here is the mocking and asserting of `navigate` (which is linked). You can see how to mock `navigate` at the top of that file [here](https://github.com/aggie-coding-club/Rev-Registration/blob/master/autoscheduler/frontend/src/tests/ui/SelectTerm.test.tsx#L15).

The steps of making the test should basically follow:
1) Open `frontend/src/tests/ui/SchedulingPage.test.tsx`
2) Add the mock that I linked above to the top of the file (don't forget to import navigate from `@reach/router`)
3) Create the `describe("stuff")` block that highlights what you _expect_ to occur from the test, then create the `test("")` block that says how you arrive at that result. It should be inside of the main `describe('Scheduling Page UI')` block. For instance, for this it could be:

```typescript
describe('Redirects to main page', () => {
   test('when term is null', () => {...});
});
```

4) Setup the tests. You should be able to basically copy/paste the [first SchedulingPage test](https://github.com/aggie-coding-club/Rev-Registration/blob/master/autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx#L18) (`indicates that there are no schedules to show - when there are no schedules to show`), and just change the `expect(...)` at the end to the one I linked from `SelectTerm.test.tsx`

Frontend testing can be super complicated, so let us know if you have any issues! For reference, you can view our "unit testing standards" on the [wiki here](https://github.com/aggie-coding-club/Rev-Registration/wiki/Unit-Testing-Standards).
