### ISSUE TITLE
Handle invalid routes / implement 404 page

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#302]
Currently our React router does a blind catch of all routes. We need to make it so that it catches invalid routes and either redirects you to the home page or shows a 404 error.

**Comment by firejake308** [comment]
I was gonna make a Figma design for this, but it's literally going to be a clone of the `<HelpText />` box with title text that says Page Not Found and no description. Does that sound good to y'all?
