### ISSUE TITLE
Prevent sending of empty course card for sessions

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#325]
Not sure how this happened, but currently my sessions on the deployment site has 1 card with `CSCE 121`, and the rest with no course in them. What `get_last_sessions` is returning currently:

```json
[
   {
      "course":"CSCE 121 - INTRO PGM DESIGN CONCEPT",
      "customizationLevel":0,
      "sections":[]
   },
   {
      "course":"",
      "customizationLevel":0,
      "sections":[]
   },
   {
      "course":"",
      "customizationLevel":0,
      "sections":[]
   }
]
```

And here's what it looks like (as you can guess):
![chrome_4UmsAIqX7Q.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/04c92452-fa6e-492a-a76d-9c6f3e58f8f2)

**Comment by ryan-conn** [comment]
To fix this, we can just not save course cards with no title
