### ISSUE TITLE
Add Twitter metadata

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Rev-Registration#332]
Having rich previews will make out website more marketable to new users. To do so, we could use [Twitter's summary metadata](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary) to achieve something that looks like this:
![image](https://user-images.githubusercontent.com/10082177/91792094-56ce9b00-ebda-11ea-85c8-41222225aa2a.png)

**Comment by gannonprudhomme** [comment]
Should also add the `<meta name="keywords" content="Search keywords here"> tag, might help with searching.
I also think the description is done through `<meta name="description" content="description here">
