### ISSUE TITLE
Add SSL Certificate to domain so we can use https

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#335]
- It currently says "not secure", presumably b/c it doesn't use https - need to make it not say this

**Comment by ryan-conn** [comment]
> Navigation to http://revregistration.com doesn't work
Are you sure? I tried in firefox, chrome, and edge, and they all worked (even without the http://)

**Comment by gannonprudhomme** [comment]
Oh shit it seems like it's working now you're right - I'm positive it wasn't working before, as I changed the GitHub URL to it and it didn't work. Guess Google Domains resolved itself in the night, will remove that part

**Comment by gannonprudhomme** [comment]
Look at https://letsencrypt.org
