### ISSUE TITLE
Add sorting to SectionSelect

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#353]
I feel like you should be able to sort courses during SectionSelect (e.g. if you did actually want them in pure section order), as it would probably help.

Might also be nice to have a filter to ignore sections that intersected with your marked availabilities.

I do think we'd have to get really clever with this design, as the SectionSelect is already pretty cluttered as is

**Comment by gannonprudhomme** [comment]
Changing this to be only sort, and putting filters in a different task

**Comment by firejake308** [comment]
![image](https://user-images.githubusercontent.com/10082177/93726540-3744e580-fb7c-11ea-9646-d802d52c5243.png)
