### ISSUE TITLE
Fix text when there are no honors or online sections for a class

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#356]
I noticed recently that the text for when there aren't any honors/online sections is a bit off:
![image](https://user-images.githubusercontent.com/28655462/93557515-ca91d700-f940-11ea-82d9-dd6f886ef9da.png)
It says "no honors or online courses" instead of "sections", and there's no margin/padding on the right.

**Comment by gannonprudhomme** [comment]
Added `good-first-issue` as this should be a pretty quick fix
