### ISSUE TITLE
Catch get_full_name 400 error in frontend

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#358]
Currently if you're not logged in `sessions/get_full_name` returns a 400 error. This functionality is fine, ~~however we don't have a catch so it ends up being shown in the console.~~
![chrome_SbRIhOuX8E.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/18eeaa8b-941a-4382-99d6-74fbd45e5716)

**Comment by ryan-conn** [comment]
I looked it up, and both chrome and firefox still log 4xx errors even with an error handler (you can verify this by going to the logout button branch, where an error handler was added but the "error" still gets logged). If we don't want it to show up, the only way is to give an ok status from the backend, then have some way on the frontend to tell that the response corresponds to the user not being logged in

**Comment by gannonprudhomme** [comment]
Yeah I think it just comes down to what is actually better REST/HTTP practice imo - if a 400 is a bad way of giving a falsy value then we could probably just switch to something else. Instinctively I just don't like being the error logged
