### ISSUE TITLE
Ordering of meetings

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Rev-Registration#359]
As you can see in the image below, sometimes, lectures are shown before labs, and other times, labs are shown before lectures. I feel like it would be better to have a consistent order for meetings (probably lecture before lab). What do y'all think?

![image](https://user-images.githubusercontent.com/10082177/93714378-e4414300-fb27-11ea-927f-67e9b85e6da7.png)

**Comment by gannonprudhomme** [comment]
Yeah this is something that's bugged me for awhile so definitely down on fixing it. Could probably mark this as good-first-issue since it's just a sort.

**Comment by ryan-conn** [comment]
I agree with you and Gannon, this would be a nice QOL update to make the cards more consistent and ensure that the most important meetings are shown first.

**Comment by gannonprudhomme** [comment]
Given that there really isn't a super obvious metric for sorting this (other than that we want it to be LEC -> LAB -> EXAM), I'd propose we sort it by how much each of the meeting types there are (which Carlos did in a query a bit ago, you can see it on the [wiki here](https://github.com/aggie-coding-club/Rev-Registration/wiki/Meeting-Types)). Copying/pasting the table from that wiki page just to save us some time. 

| count | meeting type | meeting type description |
|-------|--------------|--------------------------|
| 8072  | LEC          | Lecture                  |
| 3719  | LAB          | Laboratory               |
| 2345  | RES          | Research                 |
| 1401  | EXAM         | Examination              |
| 864   | INS          | Independent Study        |
| 467   | SEM          | Seminar                  |
| 398   | PRAC         | Practicum                |
| 280   | REC          | Recitation               |
| 144   | CLD          | Clinic                   |
| 9     | CMP          | Competition              |
| 6     | PRL          | Private Lesson           |
| 2     | CLAS         | Class                    |
| 1     | INT          | Internship               |

The top-most (LEC) should show first, and the bottom-most (INT) goes last.

**Comment by gannonprudhomme** [comment]
Mentioned it earlier today, but it should basically boil down to adding a `.sort` to [this object in `SectionSelect.tsx`](https://github.com/aggie-coding-club/Rev-Registration/blob/master/autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx#L164)
