### ISSUE TITLE
Improve SectionSelect performance

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#360]
As discovered in #357, when courses have a lot of sections (i.e. MATH-151) it can cause the selecting of the sections perform pretty slowly

Gif of the problem. Note that I'm spamming click anytime I'm hovering over the sections
![93628433-2ba2c480-f9ac-11ea-9f3f-f6c0812b0327.gif](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/de5ac1b5-5ed5-4e02-a8a8-6a35cd2b0e14)

**Comment by ryan-conn** [comment]
The Material UI documentation has a section on list virtualization that could really help with this:
https://material-ui.com/components/lists/#virtualized-list
This blog post also seems to have a good solution, it looks more complicated so if we run into some issues with the first solution then this might be the way to go:
https://mbrowndev.com/how-to-improve-material-ui-list-performance

**Comment by firejake308** [comment]
So there are 2 libraries that I've found for virtualization: `react-window` and `react-virtuoso`. `react-window` is more performant but `react-virtuoso` supports dynamically measuring height and sticky headers, so I'm leaning towards `react-virtuoso`. Here's a comparison between the two.

|Window|Virtuoso|
|--|--|
|![window](https://user-images.githubusercontent.com/10082177/94469022-f7d55500-018a-11eb-91d3-1433a037eaea.png)|![virtuoso](https://user-images.githubusercontent.com/10082177/94468451-0e2ee100-018a-11eb-8817-42258c7ddfd4.png)|

**Comment by gannonprudhomme** [comment]
I think I'll have to see how it feels when we actually use it, but if they noticeably disappear/reappear then I might just be fine sticking with it being laggy (i.e. doing nothing), as most people probably won't be able to notice that it's laggy (can really only tell when you spam click a card with a bunch of sections like MATH 151), but it will be super obvious if sections disappear/reappear upon scroll.
