### ISSUE TITLE
Change time formatting to use AM/PM on frontend

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#371]
Due to the increase in late classes (or perceived increase), I think we can no longer be confident that people will be able to tell if a time is AM/PM. For instance, this exam is 8:30 PM - 10:30 PM, but just by seeing that I would not guess that.

![chrome_AQsH2ifiPC.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/18688ec1-0a53-4087-a27e-74029c352a97)

If only we Americans used 24 hour time :cry: (haha jk screw 24 hour time AM/PM RULES)

**Comment by firejake308** [comment]
Do we want AM)PM for both times, just the start time, or just the end time? Both times takes up more space, but having only one time marked as AM/PM could be confusing

**Comment by gannonprudhomme** [comment]
I could see only having one AM/PM working, but I think we'll just have to see how it feels like in practice.
