### ISSUE TITLE
Make sure throttles complete before closing in chrome

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#372]
Due to the way chrome handles `beforeunload` events, there's currently no guarantee that functions (such as saving course cards) will complete before the tab is closed.

Making the events called in `beforeunload` synchronous should fix this, but I tried to await the fetch and it still didn't work, so going that route will require more looking into.

We could alternatively create an alert when closing the tab on the scheduling page, but Gannon said he doesn't really like this so if there's another way we can think of then we should go with it.

**Comment by firejake308** [comment]
Synchronous HTTP requests have been deprecated in Firefox and Edge, but they might still work on Chrome. [Source](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests)
