### ISSUE TITLE
New color scheme for sections on schedule

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Rev-Registration#374]
The current color scheme for the classes is a little dificult for users to quickly interpret, since all classes are some shade of maroon. We could replace them with the colors of the rainbow, which would make it much faster to differentiate between classes, but it risks losing visual appeal. Therefore, my plan is ot use [colormind.io](https://colormind.io) to look for colors that are distributed along the rainbow but "fit" well into our overall maroon theme.

**Comment by firejake308** [comment]
Here's one that looks interesting:
![image](https://user-images.githubusercontent.com/10082177/94442198-4bcf4200-0169-11eb-854c-e937832e9c36.png)

**Comment by firejake308** [comment]
Some more:
![image](https://user-images.githubusercontent.com/10082177/94442487-a23c8080-0169-11eb-85dd-50619e81c6d1.png)

**Comment by firejake308** [comment]
Okay, this should be enough:
![image](https://user-images.githubusercontent.com/10082177/94442658-d57f0f80-0169-11eb-9bad-1d5dfc26553e.png)

**Comment by ryan-conn** [comment]
I'd say I like these the most (tried to only pick ones that had decent contrast with each other): 
![image](https://user-images.githubusercontent.com/28655462/94443706-1af00c80-016b-11eb-8e21-ba289b678863.png)

**Comment by gannonprudhomme** [comment]
I think the bottom left and bottom right that ryan just sent are a bit too similar, otherwise I think they're fine

**Comment by firejake308** [comment]
How does this look to y'all?

![image](https://user-images.githubusercontent.com/10082177/94705372-9639f580-0306-11eb-8ccd-bff3aac7697c.png)

**Comment by gannonprudhomme** [comment]
I think at a glance the colors for `CSCE 121-520` and `BIOL 111-204` are a bit too close (at least on the SchedulePreview, not as much on the Schedule itself), otherwise I think this is probably good for the most part?

**Comment by gannonprudhomme** [comment]
Not sure if that website does it, but we need to make sure that the colors are able to be differentiated by color blind people. Could always have a color-blind specific mode, but I figure why not just make it easy to see by color-blind people by default.

**Comment by gannonprudhomme** [comment]
Also, could you show a quick mockup with rainbow colors? Cause instinctively that's the thing I feel like we should go to.

Could also try out using the colors we use the grade distribution, as those are colors we already use.

**Comment by firejake308** [comment]
Here are the grade distro colors:
![image](https://user-images.githubusercontent.com/10082177/97122788-7247b500-16f6-11eb-84b7-89608bf904ce.png)

**Comment by firejake308** [comment]
Straight rainbow colors:

![image](https://user-images.githubusercontent.com/10082177/97122925-319c6b80-16f7-11eb-8751-bf2974681671.png)

**Comment by firejake308** [comment]
Here's my latest render. Possible conflicts I could see are blue/turquoise/green, orange/red, red/purple, purple/dark brown. One thing to note is that I increased the brightness on the purple in order to increase the contrast with the dark brown and red, but this makes it stand out a little.

![image](https://user-images.githubusercontent.com/10082177/97513583-ade2b900-195a-11eb-954b-e943db219d60.png)
