### ISSUE TITLE
Filter by major requirement

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Rev-Registration#381]
CHEM classes have 4xx numbered sections that are only open to CHEM majors. Many other majors also take the same classes, but take one of the 5xx sections that are open to all majors. I just ran into an issue where it gave me a 4xx section that I wouldn't be able to take, and the only way to fix this was to manually select every section that wasn't 4xx. I think we should add a Basic Option to filter sections that are limited to the major. This would probably require scraping an additional field from Howdy.

**Comment by ryan-conn** [comment]
Too much effort for not much gain
