### ISSUE TITLE
useMemo for section select when expanding/collapsing, and switching between basic/section select

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#387]
Currently if you open a course card with a lot of sections, it will have to rerender them all whenever you expand the card, or when you switch from basic to section select. We should be able to `useMemo` to memoize the contents of the expanded course card/section select, and avoid a rerender if the sections haven't changed.

**Comment by gannonprudhomme** [comment]
Going to prioritize this, as I've been getting frustrated with how long KINE 199 SectionSelect's take to render
