### ISSUE TITLE
Add left/right border to MiniSchedule

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#416]
One of the things my roommate suggested when I was getting his feedback was he wanted the MiniSchedule's to have a border around them. I added left/right borders to the "calender rows" I quite like what it looks like:

![chrome_KHQkNy9KjW.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/52c22272-c58e-4039-bbd7-9509d23a0bd4)

Will probably want to make it not have a left/right border on the last one though

**Comment by firejake308** [comment]
Needs one on the bottom too

**Comment by gannonprudhomme** [comment]
I'm doing this b/c it'll be fast and I think it's been bugging me for awhile

**Comment by firejake308** [comment]
>it'll be quick

famous last words
