### ISSUE TITLE
Scrape instructional methods

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#431]
We need to add an instructional method column to the section model and determine the instructional method from json while parsing so that we can accurately show users the instructional methods for sections.

**Comment by gannonprudhomme** [comment]
Are you gonna have instructional method just be a string? 

Also, are we going to simplify them? E.g. "mixed F2F with remote" would just be "mixed"

**Comment by ryan-conn** [comment]
> Are you gonna have instructional method just be a string?
Yes, I think this would be the best way to do it.
> Also, are we going to simplify them? E.g. "mixed F2F with remote" would just be "mixed"
I'm sure that we'll want to shorten some of them, especially "Traditional Face-to-face (F2F)" which is ridiculously long. It would probably be better to do this on the backend rather than the frontend since that would slow down rendering and make our requests bigger, do you agree?
