### ISSUE TITLE
Show instructional methods next to section numbers

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#432]
To deal with the fact that there are now 5 instructional methods that are used for thousands of sections, we need to display this information to users. After #431, we should display the instructional method in a similar way to the following:
![image](https://user-images.githubusercontent.com/28655462/97244413-adb1b480-17c6-11eb-8ef5-dc76c1403c8f.png)
Note that we'll probably have to refactor section info to use `display: grid` instead of a table, as tables simply lack the flexibility to clearly display long instructional methods alongside remaining seats on low resolutions.

**Comment by gannonprudhomme** [comment]
Would you mind showing a mockup using the icons Adel mocked up in Discord? For the ones that are grouped together, we could have a tooltip that would show up when hovering over either of them.

I'm assuming you just made this on a whim? There's "face-to-face" at the top and "traditional face to face (f2f)" at the bottom lol
