### ISSUE TITLE
Remove the "This website is currently WIP" from landing page

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#506]
We should remove the "This website is currently WIP, so if you..." from the landing page. This removal basically signifies the official launch of the website, as well as us entering long-term-support mode

![chrome_xaJsXirsYC.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/854b2ef2-c617-46e3-9801-9b7bbd1c9029)

**Comment by ryan-conn** [comment]
also put a period after the last space :)
