### ISSUE TITLE
Make the website semi-functional on mobile

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#522]
Although we are of course not going to make a mobile website, we should at least make the site _semi_ functional on mobile - enough to be able to show people and such. Especially since when we advertise the site (e.g. Reddit, GroupMe's), most people are going to be on their phones when they click on the link.

- Should we just entirely disable availabilities?
  - I’d imagine not but it’s basically impossible to use due to touch input + small screen size
- Doesn’t scroll well for course cards, not sure how to fix
- Should format correctly in landscape

**Comment by firejake308** [comment]
|Landing Page (before)|Landing Page (after)|Scheduling Page (before)|Scheduling Page (after)|
|--|--|--|--|
|![localhost_8000_(iPhone 5_SE) (2)](https://user-images.githubusercontent.com/10082177/115938273-aad70a00-a45f-11eb-962c-227f7ce0357e.png)|![127 0 0 1_8000_(iPhone 5_SE)](https://user-images.githubusercontent.com/10082177/115937905-ae1dc600-a45e-11eb-8b44-c889c5ad072c.png)|![localhost_8000_schedule(iPhone 5_SE)](https://user-images.githubusercontent.com/10082177/115938297-bfb39d80-a45f-11eb-964f-97a054bfaf06.png)|![127 0 0 1_8000_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/10082177/115937914-b118b680-a45e-11eb-90eb-d72ebfb09df4.png)|

The main body is looking better now, but I'm not sure what to do about the nav bar. Should we hide the select term or the login with google? Or both?

**Comment by gannonprudhomme** [comment]
Definitely the select term - it's really just more of a bonus, and the site can function completely fine without it (just requires a few extra steps)

**Comment by ryan-conn** [comment]
> The main body is looking better now, but I'm not sure what to do about the nav bar. Should we hide the select term or the login with google? Or both?

I think hiding the term select is a good idea, but logging in is a key part of the website (especially since the main use case for mobile I see is logging in real quick to check your schedules), so I think it should be kept.

Also something I want to point out is that since I'm working on #517 right now, changes to the navbar will probably be pretty messy if you do it before that's merged. I just made a PR for it (I thought I had before the meeting but apparently I forgot) that's pretty short, I'll leave it up to you to decide how to handle it (base off my branch, wait for merge, etc)

**Comment by firejake308** [comment]
Which layout looks better on iPad? Should it be same as desktop or mobile? Leaning toward mobile right now
|Desktop Layout on iPad|Mobile Layout on iPad|
|--|--|
|![localhost_8000_(iPad) (1)](https://user-images.githubusercontent.com/10082177/116004587-08d33100-a5c9-11eb-82b0-7ff3ecb75fd0.png)|![localhost_8000_schedule(iPad) (1)](https://user-images.githubusercontent.com/10082177/116004584-0375e680-a5c9-11eb-93df-091f0a88d305.png)|

**Comment by gannonprudhomme** [comment]
I would say right for portrait, but I do think that landscape it should look like the left one (if that's possible / not to difficult), as it should have enough space when it's in landscape (especially if we shrink the schedule)

**Comment by firejake308** [comment]
Ryan mentioned that he would want to be able to use availablities, as it's the only thing preventing the site from being fully usable on mobile. Would require more work than the media queries in #544, but it's worth considering as a separate PR
