### ISSUE TITLE
Handle remove transitions more gracefully

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Rev-Registration#548]
I found one bug in this, which is that whenever you close a card, the next time you expand one it won't play the animation. This happens on the next time a card is expanded whether there was one expanded when you closed a card or not.

-Ryan
![bug](https://user-images.githubusercontent.com/28655462/116306361-94d08e80-a76a-11eb-8bb2-cc0c60aee68c.gif)

**Comment by gannonprudhomme** [comment]
also the course titles shift when you expand/collapse cards

**Comment by firejake308** [comment]
@gannonprudhomme Just to confirm, are you referring to the fact that there is 3px less space between the delete icon and "Remove" compared to the space between the delete icon and "BIOL 107"?

![transition](https://user-images.githubusercontent.com/10082177/116304377-2094eb80-a768-11eb-9775-9e09b20259d3.gif)

**Comment by gannonprudhomme** [comment]
Nope - previously when you would transition the cards, the course title (`CARC 300 - CARC STUDY AB...`) would shift up and down, but it doesn't seem like it's doing it anymore. Also I can't find my original post on #474 where I showed it so maybe I'm just going crazy

**Comment by firejake308** [comment]
> I found one bug in this, which is that whenever you ~close~ *remove* a card, the next time you expand one it won't play the animation. This happens on the next time a card is expanded whether there was one expanded when you closed a card or not.

@ryan-conn did you mean to say remove instead of close? If so, I can think of a potential fix

**Comment by ryan-conn** [comment]
Yeah that's what I meant, I added a gif to the description with both cases it pops up
