### ISSUE TITLE
Generate schedules with exclusive courses?

### ISSUE THREAD

**Issue by tcheinen** [aggie-coding-club/Rev-Registration#550]
I'm picking core classes at the moment and a decent chunk of my selection process is "look at building, times, gpa distributions". I've narrowed it down to courses that look vaguely interested but it might still be useful to be able to add multiple courses which are exclusive and generate possible schedules which contain only a single one of these courses.

**Comment by gannonprudhomme** [comment]
Hey Teddy,
First, thanks for submitting an issue! We love hearing suggestions, and you're the first user to do so, which we really appreciate :)

Second, while it's not exactly the same, we

 currently have a pull request for disabling courses (#502), which allows you to disable a course and prevent it from being generated in the schedule. As such, I believe that to achieve the functionality you want, you'd just have to manually switch between courses by disabling the ones you don't want and enabling the ones you do. It does seem like a bit more work/steps to achieve what you're looking for, but I think it allows for greater flexibility instead. Let us know if you think the use cases are different though.

Here's a gif of it in action:

**Comment by gannonprudhomme** [comment]
Just btw @tcheinen this feature has been merged, so you should be able to see it on https://revregistration.com/ !
