### ISSUE TITLE
total hours counter

### ISSUE THREAD

**Issue by AnnySuho** [aggie-coding-club/Rev-Registration#557]
feature that adds a counter for cumulative hours generated in the schedule somewhere in the UI

**Comment by firejake308** [comment]
Ooh we actually talked about this in development, but we could never find a good place to put it. Do you have any ideas for a non-intrusive location for the hour counter?

**Comment by AnnySuho** [comment]
not particularly as long as its easily visible that would be good.
![image](https://user-images.githubusercontent.com/51311762/116454901-12a5a000-a826-11eb-9d7e-ac43e11da84e.png)
here are some suggestions that i think would be pretty good

**Comment by gannonprudhomme** [comment]
Closed per #595
