### ISSUE TITLE
allow clicking course in the schedule graphic

### ISSUE THREAD

**Issue by AnnySuho** [aggie-coding-club/Rev-Registration#559]
more of a design choice kind of thing maybe but it would be nice to be able to click (ill even settle for hover honestly) the course in the graphic schedule area and get relevant information popup. i know at the moment its probably because the other (helpful) feature for blocking up time is a thing which causes clicking to behave the way it does currently. maybe make that blocking time a thing you first select and then click to block off so by default anytime you (might accidentally) click its not drawing blocked off times?

**Comment by firejake308** [comment]
One idea that we had was to have it so that clicking on a course would open the corresponding card and scroll to that section. Would that work for you?

**Comment by gannonprudhomme** [comment]
> One idea that we had was to have it so that clicking on a course would open the corresponding card and scroll to that section. Would that work for you?

Filled in #467, but not sure if this fits it exactly or not

**Comment by AnnySuho** [comment]
sure that sounds fine.

> >Would that work for you?
lol this makes it sound like im some sort of important client or something xd

**Comment by gannonprudhomme** [comment]
> sure that sounds fine.
> 
> > > Would that work for you?
> > > lol this makes it sound like im some sort of important client or something xd

You are! We're making this for our fellow students, after all

**Comment by gannonprudhomme** [comment]
Closing in favor of #467
