### ISSUE TITLE
allow bad schedules to be generated

### ISSUE THREAD

**Issue by AnnySuho** [aggie-coding-club/Rev-Registration#560]
![image](https://user-images.githubusercontent.com/51311762/116455638-edfdf800-a826-11eb-8116-4abcf5edc354.png)
im sure this was an intentional design choice but i personally think its incredibly useful to display schedules that are "impossible". currently the behavior is that it wont generate a schedule that is not possible. the reason why i would find this feature useful is i want to be able to visually see (after all thats why im using a graphic calendar and not just imagining it in my head) a physical conflict of courses. by being able to see what wont work out, i am forced to make a decision (that the graphic calendar helped me see). not so helpful when the error message is simply "no schedules possible" (if i added all my courses at once and then clicked generate schedules i dont even know which courses are conflicting....).

not sure what a fix is as i would have to look at the source code to see how the logic is currently implemented. but as this is clearly a core feature, id imagine a change to be somewhat of an overhaul....

**Comment by ryan-conn** [comment]
I'm marking this as wontfix for a couple reasons:
- I don't see this being much more useful than just showing an error message - there are many possible ways overlaps would be made (two courses conflict, three do, various combinations all conflict, etc.), and simply showing random schedules that don't work will not be useful in the vast majority of situations
- It would require a good amount of frontend work to show overlapping meetings
