### ISSUE TITLE
change login account

### ISSUE THREAD

**Issue by AnnySuho** [aggie-coding-club/Rev-Registration#561]
after logging in and authenticating once and logging out, my guess is probably somewhere some sort of (session) data is stored. because after clicking the login button, i am not asked to enter my credentials and get authenticated again (immediately connected with whatever previous login i used first). this should not be a feature (i hope) as i want to log in with switch the google account i am on but currently i have no choice but to use whichever one i used first.

(another more UX suggestion i have is to make the authentication a popup but that might make it less mobile friendly so idk if you guys even want to handle that if yall want a new issue to be submitted i can but its more of a small personal thing)

**Comment by gannonprudhomme** [comment]
Great suggestion! This is definitely something we can do

> (another more UX suggestion i have is to make the authentication a popup but that might make it less mobile friendly so idk if you guys even want to handle that if yall want a new issue to be submitted i can but its more of a small personal thing)

I think this might be slightly harder to do (actually thought of it awhile ago in #294, but never ended up doing it), but it's we'll keep it in mind!

**Comment by ryan-conn** [comment]
We use Google OAuth to handle logging in and whenever I sign in it gives me a list of accounts to use like the following:
![image](https://user-images.githubusercontent.com/28655462/116457769-6f568a00-a829-11eb-9b58-62024751aab4.png)
My guess is that you're only logged in to a single google account, which means google will assume you want to use that account and bypass the account select screen (I've made a branch containing a fix for this behavior). Let me know if that isn't the case though

**Comment by AnnySuho** [comment]
Im not sure we are exactly 100% on the same page (although your latter description sounds like what I am describing).

steps to reproduce:
1) i click login
2) enter my email/password for user account 1, google does oauth in the background
3) im now logged in with account 1 and now i click log out because i want to switch to account 2
4) i am now logged out and I want to log in with account 2
5) i cant and i am automatically logged back in with account 1

if the fix that you are describing is this then thats good

**Comment by ryan-conn** [comment]
Yeah that's the fix does, it will always prompt you with the account to login with like the screen below:
![image](https://user-images.githubusercontent.com/28655462/116460120-4c79a500-a82c-11eb-9c42-e66fa55213d9.png)

**Comment by AnnySuho** [comment]
> My guess is that you're only logged in to a single google account, which means google will assume you want to use that account and bypass the account select screen

wow is that seriously a google sided thing.... wack
