### ISSUE TITLE
Use no arrow for tooltip on GPA in GradeDist

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#572]
![image.png](https://images.zenhubusercontent.com/5da358de33f74500019c3b7f/009bccee-2e6e-44e6-9074-ffe8ce33474f)

Either need to change the arrow direction or just make it use the no arrow Tooltip (might as well for consistencies sake)

**Comment by firejake308** [comment]
The positioning is also funky, in that it covers up the GPA text. Will removing the arrow fix that?

**Comment by gannonprudhomme** [comment]
> The positioning is also funky, in that it covers up the GPA text. Will removing the arrow fix that?

Was figuring it would - I assumed the arrow was forcing it to remain above it, but it clearly can't

**Comment by ryan-conn** [comment]
Do together with #571
