### ISSUE TITLE
Credit hours for law courses are incorrect

### ISSUE THREAD

**Issue by andrew-fennell** [aggie-coding-club/Rev-Registration#632]
## Issue
Credit hours shown for LAW courses are incorrect. The hours on Rev Registration and Howdy don't match.

### Incorrect credit hours on Rev Registration
![Rev_Registration_Credit_Hours](https://user-images.githubusercontent.com/28690153/160534012-51498953-f471-429a-b51d-047276430423.jpeg)

### Credit hours shown on Howdy
![Howdy_Credit_Hours](https://user-images.githubusercontent.com/28690153/160533997-dd70ce15-6166-4b4f-8bb2-1964e463bc43.jpeg)

## Expected Outcome
LAW course credit hours that match Howdy.

**Comment by gannonprudhomme** [comment]
Nice catch @andrew-fennell 😄

So this is a case that we don't see often in under-grad: actual variance/range in credit hours. For most of these courses they actually have a range of credit hours, as you can see here (the `Credit hours: 2 TO 3`):

|LAW 7401|LAW 7452|
|--|--|
|![chrome_kHH1gW7mb5](https://user-images.githubusercontent.com/7295783/160548323-4fa56e68-96ed-4ad2-aa44-a64993696721.png)|![chrome_ux7GynFN6X](https://user-images.githubusercontent.com/7295783/160548173-faf3ac36-a0e2-4171-bfff-adf669200683.png)|

The background: there isn't _really_ a "main" credit hour property, there's two:, `creditHourLow` and `creditHourHigh`. And in most cases, `creditHourHigh` was `null` and `creditHourLow` was the actual credit hours, so we chose this to represent the credit hours. This is the reason you see the difference - we're choosing `creditHourLow`, while Howdy is using `creditHours`/`creditHourHigh`. (there is actually a main/central `creditHours` property that was added to section data after like Spring 2021 or so, but I actually like the below solution better than using it to be accurate [plus its more work =P])

However it's tricky to actually chose one or the other - for some courses they'll have a range of [1, 23] and we obviously don't want to pick 23 hours for it (e.g. CVEN 691). As such, the solution we came up with was instead to just show the range to the user! Going to do one of these two (lmk if you have a preference!):

|Using dashes|Using "to"|
|--|--|
|![chrome_vaWzjo7w7B](https://user-images.githubusercontent.com/7295783/160731878-fd93e743-bb8f-4621-8cc0-6a289759aa8c.png)|![chrome_OZaWKP0uyF](https://user-images.githubusercontent.com/7295783/160731885-c6f360a0-0d6a-40b5-b6bd-db2c00fe644a.png)|

Potential downside being that classes with huge ranges like research (491, 691) & directed studies courses (485, 685) might cause confusion, but I'm gonna leave that up to the user to figure out (it's not our fault after all hehe)

![chrome_oSEK1CwYD1](https://user-images.githubusercontent.com/7295783/160732204-bf9d2a6c-cddd-43cd-b1b5-974d6e075c14.png)


Thanks for the report Andrew! We appreciate it :)

**Comment by andrew-fennell** [comment]
I think that is a great solution for a strange (and probably rare) edge case.
